project_id = "ghpljdgecjmhkwkfctgy"

[functions.perplexity-research]
verify_jwt = true

[functions.generate-case-strategy]
verify_jwt = true

[functions.analyze-document-context]
verify_jwt = true

[functions.search-similar-cases]
verify_jwt = true