project_id = "ghpljdgecjmhkwkfctgy"

[functions.ai-agent-coordinator]
verify_jwt = false

[functions.validate-and-save-legal-analysis]
verify_jwt = true

[functions.perplexity-research]
verify_jwt = true

[functions.generate-case-strategy]
verify_jwt = true

[functions.analyze-document-context]
verify_jwt = true

[functions.search-similar-cases]
verify_jwt = true

[functions.harvest-legal-pdf]
verify_jwt = true

[functions.process-pdf-document]
verify_jwt = true

[functions.generate-legal-analysis]
verify_jwt = false

[functions.cleanup-unvalidated-analyses]
verify_jwt = false