project_id = "ghpljdgecjmhkwkfctgy"

[functions.ai-agent-coordinator]
verify_jwt = true

[functions.perplexity-research]
verify_jwt = true

[functions.search-similar-cases]
verify_jwt = true

[functions.review-uploaded-document]
verify_jwt = true

[functions.statute-retrieval]
verify_jwt = false

[functions.export-case-analysis]
verify_jwt = true

[functions.export-quick-consult]
verify_jwt = true